name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.2.2"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Download Espanso
        run: |
          wget https://github.com/federico-terzi/espanso/releases/download/v2.1.8/espanso-debian-x11-amd64.deb
      - name: Install Espanso
        run: sudo apt install ./espanso-debian-x11-amd64.deb
      - name: Register espanso as service
        run: espanso service register
      - name: Install X11
        run: sudo apt-get install xorg openbox
# Espanso start goes here if this doesnt work
      - name: Log Espanso State (for debugging)
        run: espanso log
      - name: Run the default task
        run: bundle exec rake
      - name: RSpec
        run: bundle exec rspec
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
