name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: macos-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.2.2"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Tap Espanso homebrew keg
        run: brew tap espanso/espanso
      - name: Install Espanso
        run: brew install espanso
# This is where it fails as of 9/28 10:15AM
      - name: Check created directories
        run: cd $HOME/'Application Support'/espanso/match/base.yml
        run: ls -a
      - name: Start Espanso
        run: espanso service start --unmanaged
      - name: Log Espanso State (for debugging)
        run: espanso log
      - name: Debug with tmate on failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
      - name: Run the default task
        run: bundle exec rake
      - name: RSpec
        run: bundle exec rspec
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
